language: php
dist: trusty

php:
  - '5.5'
  - '5.6'

cache:
  directories:
    - vendor

install: composer install

script: vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
